### ISSUE TITLE
ارسال پیام آنی و پوش نوتیفیکیشن از اندروید به وب و بالعکس

### ISSUE THREAD

**Issue by tahlilgar** [chabok-io/chabok-client-android#1]
سلام 
توی نمونه کد ها ارسال پیام از وب به وب و از موبایل به موبایل امکان پذیر هست. چطور میشه از موبایل به وب و بالعکس رو هم فعال کرد؟
مثلا از وب به اندروید یک ارایه جیسون شامل پارامترهای دلخواه ارسال بشه و موبایل حتی در صورت بسته بودن برنامه آن را دریافت کند و برعکس.

**Comment by Husseinhj** [comment]
<p dir="rtl">برای ارسال پیام در چابک باید از <code>userId</code> استفاده کنید.</p>
<p dir="rtl">برای ارسال پیام از هر پلتفرمی به پلتفرمی دیگر فقط کافی هست <code>userId</code> کاربر مقصد را مشخص کنید</p>
