### ISSUE TITLE
[documentation] داده های سفارشی کاربر با امضای دوم login کار نمی کند

### ISSUE THREAD

**Issue by Hoss3inf** [chabok-io/chabok-client-android#3]
سلام. وقت بخیر
مشکلی با مستندات داشتم که 
برای ثبت داده های سفارشی کاربر، از امضای دوم متد login استفاده کردم. این متد اما، کار نمی کند. 
پس از اینکه عمیقتر در مستندات نگاه کردم، با استفاده از متد setUserAttrubutes اطلاعات کاربر را ذخیره کردم.
به نظر می رسد که متد دوم لاگین کار نمی کند. خواستم اطلاع بدم که بررسی کنید، اگر هم مشکل از طرف من هست، لطفا بهم بگید.
متشکرم

**Comment by farbod-s** [comment]
<div dir="rtl">
@Hoss3inf 
<br>
لطفا نتیجه رو اطلاع بدید تا اگر مشکلی هست برطرف کنیم و یا اگر مشکل حل شده issue رو ببندیم
<br>
ممنون
</div>
