### ISSUE TITLE
Google play console -> Security alert

### ISSUE THREAD

**Issue by ah-nili** [chabok-io/chabok-client-android#4]
Security alert
Your app contains unsafe cryptographic encryption patterns. 
Please see this[ Google Help Center article for details](https://support.google.com/faqs/answer/9450925).
Vulnerable classes:
com.adpdigital.push.AdpPushClient.encrypt

**Comment by Husseinhj** [comment]
This warning has been fixed in [version 2.18.2](https://github.com/chabok-io/chabok-client-android/releases/tag/v2.18.2).

> Note:  Please update to the [latest version](https://github.com/chabok-io/chabok-client-android/releases/tag/v3.2.0).
